name = "lebitsh"
main = "src/worker.js"
account_id = "3c0c306f81da07ae96cee78fab4a91b3"
compatibility_date = "2026-08-21"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false
logpush = true

[assets]
directory = "./web"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "none"
run_worker_first = false

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[[rules]]
type = "Text"
globs = ["**/*.sh"]
fallthrough = true

[[routes]]
pattern = "lebit.sh"
custom_domain = true
